In [2]:
import pandas as pd
from src.utils import load_object


In [3]:
transformer = load_object("artifacts\processor.pkl")

In [4]:
transformer

ColumnTransformer(transformers=[('numerical_columns',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standard_scaler',
                                                  StandardScaler())]),
                                 ['age', 'Medu', 'Fedu', 'traveltime',
                                  'studytime', 'failures', 'famrel', 'freetime',
                                  'goout', 'Dalc', 'Walc', 'health',
                                  'absences']),
                                ('categorical_columns',
                                 Pipeline(steps=[('one_hot_encoder',
                                                  OneHotEncoder()),
                                                 ('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['school', 'sex', 'address', 'famsize',
                                  'Pstatus', 'Mjob', 'Fjob', 'reason',
                                  'guardian', 'schoolsup', 'famsup', 'paid',
                                  'activities', 'nursery', 'higher', 'internet',
                                  'romantic'])])

In [8]:
processor = load_object("artifacts\processor.pkl")

In [9]:
data = data.head(1)

In [10]:
data

school sex  age address famsize Pstatus  Medu  Fedu     Mjob     Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home  teacher  ...   

  internet romantic  famrel  freetime  goout Dalc Walc health absences passed  
0       no       no       4         3      4    1    1      3        6     no  

[1 rows x 31 columns]

In [ ]:
data = data.drop

In [11]:
data = processor.fit_transform(data)

In [12]:
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
model = load_object("artifacts\model.pkl")


In [22]:
model

AdaBoostClassifier(learning_rate=0.1, n_estimators=32)

In [6]:
data = pd.read_csv("artifacts\data.csv")

In [7]:
data.head(1)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob     Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home  teacher  ...   

  internet romantic  famrel  freetime  goout Dalc Walc health absences passed  
0       no       no       4         3      4    1    1      3        6     no  

[1 rows x 31 columns]

In [6]:
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  internet romantic  famrel  freetime  goout Dalc Walc health absences passed  
0       no       no       4         3      4    1    1      3        6     no  
1      yes       no       5         3      3    1    1      3        4     no  
2      yes       no       4         3      2    2    3      3       10    yes  
3      yes      yes       3         2      2    1    1      5        2    yes  
4       no       no       4         3      2    1    2      5        4    yes  

[5 rows x 31 columns]

In [23]:
data = data.drop(columns = ["passed"],axis=1)
data.head()

AttributeError: 'numpy.ndarray' object has no attribute 'drop'

In [ ]:
data

In [8]:
data = transformer.fit_transform(data)

In [9]:
data

array([[ 1.02304645,  1.14385567,  1.36037064, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.23837976, -1.60000865, -1.39997047, ...,  1.        ,
         1.        ,  0.        ],
       [-1.33095364, -1.60000865, -1.39997047, ...,  1.        ,
         1.        ,  0.        ],
       ...,
       [ 3.37704655, -1.60000865, -1.39997047, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.02304645,  0.22923423, -0.47985677, ...,  1.        ,
         1.        ,  0.        ],
       [ 1.80771315, -1.60000865, -1.39997047, ...,  1.        ,
         1.        ,  0.        ]], shape=(395, 56))

In [10]:
from data_ingestion import DataIngestionConfig,DataIngestion
from data_transformation import DataTransformation,DataTransformationConfig
obj = DataIngestion()
train_path,test_path = obj.initiate_data_ingestion()
obj2 =  DataTransformation()
train_arr,test_arr,_ = obj2.initiate_data_transformation(train_path=train_path,test_path=test_path)

c:\machine_learning\data_science_project_college\data_transformation.py:72: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data["passed"] = train_data["passed"].replace({"yes": 1, "no": 0})
c:\machine_learning\data_science_project_college\data_transformation.py:75: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data["passed"] = test_data["passed"].replace({"yes": 1, "no": 0})


In [11]:
train_arr

array([[-0.58639605,  0.24643712,  0.42320737, ...,  0.        ,
         1.        ,  1.        ],
       [-0.58639605, -0.68063585,  0.42320737, ...,  1.        ,
         0.        ,  1.        ],
       [-0.58639605, -1.60770883,  0.42320737, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 1.77915057,  0.24643712,  0.42320737, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.20211949,  1.17351009,  0.42320737, ...,  0.        ,
         1.        ,  1.        ],
       [-1.37491159,  1.17351009,  1.35191243, ...,  1.        ,
         0.        ,  1.        ]], shape=(316, 57))

In [12]:
test_arr

array([[ 0.20211949, -0.68063585, -1.43420275, ...,  1.        ,
         0.        ,  1.        ],
       [ 0.99063503, -1.60770883, -0.50549769, ...,  0.        ,
         1.        ,  1.        ],
       [ 0.99063503,  0.24643712,  0.42320737, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-1.37491159, -0.68063585, -1.43420275, ...,  0.        ,
         1.        ,  0.        ],
       [-1.37491159,  1.17351009, -0.50549769, ...,  0.        ,
         1.        ,  1.        ],
       [ 0.20211949,  0.24643712, -0.50549769, ...,  1.        ,
         0.        ,  0.        ]], shape=(79, 57))

In [ ]:
## transformation has been done on my training dataset and testing dataset
## which means my trainming data and tetsing data is applicable for training with machine learning model

In [13]:
from src.utils import load_object

In [16]:
obj = load_object("artifacts\json_to_df.pkl")

StudentException: Error occured in python script name [c:\machine_learning\data_science_project_college\src\utils.py] line number [48] error message [Can't get attribute 'json_to_df' on <module '__main__'>]

In [20]:
import pickle
with open("artifacts/json_to_df.pkl", "rb") as f:
    loaded_json_to_df = pickle.load(f)

AttributeError: Can't get attribute 'json_to_df' on <module '__main__'>